// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Global/Header";
import Footer from "./components/Global/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        
        <main className="pt-16 pb-10 max-w-[1600px] mx-auto sm:px-10 px-4">
          <Header />
          {children}
          <Footer />
          <SpeedInsights />
        </main>
      </body>
    </html>
  );
}